#!/usr/bin/env python3
"""Render a markdown table of what xcindex's plan_rename can and cannot
find, aggregated from every *-coverage-summary.json file under
tests/coverage/. Run after `swift test` populates the summaries.

Output lands at docs/coverage.md by default. Pass --stdout to dump to
stdout instead (handy for CI step summaries).

Usage:
  scripts/render-coverage-table.py
  scripts/render-coverage-table.py --stdout
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
COVERAGE_DIR = REPO_ROOT / "tests" / "coverage"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "coverage.md"


def load_summaries() -> list[dict[str, Any]]:
    """Return one dict per coverage summary file, sorted by fixture name."""
    summaries: list[dict[str, Any]] = []
    for path in sorted(COVERAGE_DIR.glob("*coverage-summary.json")):
        with path.open() as fp:
            summaries.append({"path": path, "data": json.load(fp)})
    return summaries


def fmt_ratio(value: float | None) -> str:
    if value is None:
        return "—"
    return f"{value:.0%}" if value <= 1.0 else f"{value:.2f}"


def fmt_ms(value: float | None) -> str:
    if value is None:
        return "—"
    return f"{value:.1f} ms"


def render_summary(entry: dict[str, Any]) -> list[str]:
    data = entry["data"]
    fixture = data.get("fixture", entry["path"].stem)
    upstream = data.get("upstream")
    aggregate = data.get("aggregate", {})

    lines: list[str] = []
    header = f"### `{fixture}`"
    if upstream:
        header += f" — pinned at `{upstream.get('tag')}` (`{upstream.get('sha', '')[:12]}`)"
    lines.append(header)
    lines.append("")

    verified_count = aggregate.get("verified_symbol_count", 0)
    stub_count = aggregate.get("stub_symbol_count", 0)
    recall = aggregate.get("recall")
    precision = aggregate.get("precision")
    max_ms = aggregate.get("max_plan_elapsed_ms")

    meta_bits = []
    if verified_count or stub_count:
        meta_bits.append(f"{verified_count} verified / {stub_count} stub symbols")
    if recall is not None:
        meta_bits.append(f"recall {fmt_ratio(recall)}")
    if precision is not None:
        meta_bits.append(f"precision {fmt_ratio(precision)}")
    if max_ms is not None:
        meta_bits.append(f"max plan {fmt_ms(max_ms)}")
    if meta_bits:
        lines.append("_" + " · ".join(meta_bits) + "_")
        lines.append("")

    lines.append("| Symbol | Kind | Retrieved | Expected | Recall | Precision | Plan time | Status |")
    lines.append("| ------ | ---- | --------: | -------: | -----: | --------: | --------: | ------ |")

    per_symbol = data.get("per_symbol", [])
    for row in per_symbol:
        status = "stub" if row.get("needs_verification") else "verified"
        refusal = row.get("refusal_reason")
        if refusal:
            status = f"refused ({refusal})"
        lines.append(
            "| `{sym}` | {kind} | {ret} | {exp} | {recall} | {prec} | {ms} | {status} |".format(
                sym=row["symbol_query"],
                kind=row.get("kind", ""),
                ret=row.get("retrieved_count", "—"),
                exp=row.get("expected_count", "—"),
                recall=fmt_ratio(row.get("recall")),
                prec=fmt_ratio(row.get("precision")),
                ms=fmt_ms(row.get("plan_elapsed_ms")),
                status=status,
            )
        )
    lines.append("")
    return lines


def render(summaries: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "# Coverage",
        "",
        "What `plan_rename` finds for each pinned fixture. Generated by",
        "`scripts/render-coverage-table.py` from the `*-coverage-summary.json`",
        "files emitted by `swift test`. Don't edit by hand — rerun the",
        "script after the test suite to refresh.",
        "",
        "Rows marked `verified` have hand-curated `expected_ranges` and",
        "gate the build at recall 1.0. Rows marked `stub` are informational",
        "until a reviewer completes the second-pair-of-eyes curation",
        "described in [`tests/coverage/CONVENTIONS.md`](../tests/coverage/CONVENTIONS.md).",
        "",
    ]
    if not summaries:
        lines.append("_No coverage summaries found under `tests/coverage/`. Run `swift test` first._")
        return "\n".join(lines) + "\n"

    for entry in summaries:
        lines.extend(render_summary(entry))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Write to stdout instead of docs/coverage.md.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args()

    summaries = load_summaries()
    rendered = render(summaries)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"Wrote {args.output.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
